--- #YAML:1.0
name:                Muldis-Rosetta
version:             0.13.3
abstract:            Full-featured truly relational DBMS in Perl
license:             lgpl
author:              
    - Darren Duncan <perl@DarrenDuncan.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::MOP:                    0.84
    Moose:                         0.79
    Moose::Role:                   0.79
    MooseX::Singleton:             0.17
    namespace::clean:              0.11
    Test::Moose:                   0.79
    version:                       0.74
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
