--- #YAML:1.0
name:               Muldis-Rosetta
version:            0.14.0
abstract:           Full-featured truly relational DBMS in Perl
author:
    - Darren Duncan <perl@DarrenDuncan.net>
license:            lgpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp::Always:         0.09
    Class::MOP:           0.92
    Moose:                0.89
    Moose::Role:          0.89
    MooseX::Singleton:    0.18
    namespace::autoclean:  0.08
    Test::Moose:          0.89
    Test::More:           0.92
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
